before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/adamcstephens/mqtt-homekit-light/release:latest
      - ghcr.io/adamcstephens/mqtt-homekit-light/release:{{ .Tag }}

nfpms:
  - id: default
    maintainer: Adam Stephens <releases@valkor.net>
    description: Bridge a virtual homekit light to mqtt.
    bindir: /usr/bin
    formats:
      - deb
      - rpm
    contents:
      - src: package/mqtt-homekit-light@.service
        dst: /usr/lib/systemd/system/mqtt-homekit-light@.service
    empty_folders:
      - /etc/mqtt-homekit-light
    scripts:
      postinstall: package/postinstall.sh

snapshot:
  name_template: "{{ .Tag }}-next"
