before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - docker.pkg.github.com/adamcstephens/mqtt-homekit-light/release:latest
      - docker.pkg.github.com/adamcstephens/mqtt-homekit-light/release:{{ .Tag }}

snapshot:
  name_template: "{{ .Tag }}-next"
